### ISSUE TITLE
Conda-smithy `NoPackagesFound` error

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/conda-smithy#552] opened 2017-08-11 20:00 UTC
Upon upgrading conda-smithy to 2.3.3 from 2.3.2, `conda` also updated itself from 4.3.22 to 4.3.24. Running `conda smithy rerender`, I now get:

```
$ conda smithy rerender
Traceback (most recent call last):
  File "/Users/zzz/anaconda/bin/conda-smithy", line 4, in <module>
    import conda_smithy.cli
  File "/Users/zzz/anaconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 12, in <module>
    from conda_build.metadata import MetaData
  File "/Users/zzz/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 10, in <module>
    from .conda_interface import iteritems, PY3, text_type
  File "/Users/zzz/anaconda/lib/python2.7/site-packages/conda_build/conda_interface.py", line 22, in <module>
    from conda.resolve import MatchSpec, NoPackagesFound, Resolve, Unsatisfiable, normalized_version  # NOQA
ImportError: cannot import name NoPackagesFound
```

Downgrading back down to conda 4.3.22 resolved the issue.

**Comment by jakirkham** [comment] 2017-08-11 20:42
Probably related to if not caused by issue ( https://github.com/conda-tools/conda-build-all/issues/91 ).

**Comment by jakirkham** [comment] 2017-09-08 05:00
Should be fixed by upgrading to `conda-build-all` 1.1.1.

**Closed by jakirkham** 2017-09-08 05:00 UTC

**Comment by alimanfoo** [comment] 2017-11-28 01:06
I'm getting this error with the following installed:

```
conda                     4.3.29                   py35_0    conda-forge
conda-build               2.0.2                    py35_0  
conda-build-all           1.1.3                      py_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-smithy              2.4.3                      py_0    conda-forge
```

Does this issue need to be re-opened?

**Comment by alimanfoo** [comment] 2017-11-28 01:08
FWIW downgrading to conda=4.3.22 fixed for me too.

**Comment by jakirkham** [comment] 2017-11-28 01:33
I think updating `conda-build-all` should fix it. Should add we also have commands for doing thing like re-renderings now.

ref: https://conda-forge.org/docs/webservice.html

**Comment by alimanfoo** [comment] 2017-11-28 01:41
Ah, webservice nice. FWIW upgrading conda-build looks to have done it.
