### ISSUE TITLE
Linter failed to lint the recipe

### ISSUE THREAD

**Issue by xhochy** [conda-forge/conda-smithy#589] opened 2017-09-28 12:09 UTC
I have a failure in https://github.com/conda-forge/arrow-cpp-feedstock/pull/39#issuecomment-332802319

Is there anything I can provide on information so that this can be fixed? (How can I find out what actually failed?)

**Comment by isuruf** [comment] 2017-09-28 13:49
```
2017-09-28T10:58:27.286576+00:00 app[web.1]: Traceback (most recent call last):
2017-09-28T10:58:27.286576+00:00 app[web.1]:   File "/app/.conda/lib/python3.5/site-packages/tornado/web.py", line 1509, in _execute
2017-09-28T10:58:27.286578+00:00 app[web.1]:     result = method(*self.path_args, **self.path_kwargs)
2017-09-28T10:58:27.286579+00:00 app[web.1]:   File "/app/conda_forge_webservices/webapp.py", line 81, in post
2017-09-28T10:58:27.286580+00:00 app[web.1]:     repo_name == 'staged-recipes')
2017-09-28T10:58:27.286580+00:00 app[web.1]:   File "/app/conda_forge_webservices/linting.py", line 95, in compute_lint_message
2017-09-28T10:58:27.286581+00:00 app[web.1]:     ref_merge.checkout(force=True)
2017-09-28T10:58:27.286581+00:00 app[web.1]: UnboundLocalError: local variable 'ref_merge' referenced before assignment
```

**Comment by jakirkham** [comment] 2017-09-28 15:27
Thanks for the log. Means that it was this [line]( https://github.com/conda-forge/conda-forge-webservices/blob/8e468306d321ba1cbd992bdc883400cfed724247/conda_forge_webservices/linting.py#L95 ). Also means that this [step]( https://github.com/conda-forge/conda-forge-webservices/blob/8e468306d321ba1cbd992bdc883400cfed724247/conda_forge_webservices/linting.py#L36-L41 ) failed. Would like to understand more why that step failed. Should we move this over to webservices given the cause of the issue?

**Comment by jakirkham** [comment] 2017-10-14 23:11
Closing as this is being tracked in issue ( https://github.com/conda-forge/conda-forge-webservices/issues/126 ) (where the source code for this error is). Thanks @xhochy!

**Closed by jakirkham** 2017-10-14 23:11 UTC
Labels: linter
