### ISSUE TITLE
builds on azure for windows finds wrong compiler

### ISSUE THREAD

**Issue by looooo** [conda-forge/conda-smithy#1064] opened 2019-04-26 07:31 UTC
https://github.com/conda-forge/simage-feedstock/pull/7
```
CMake Error at D:/bld/simage_1556231733385/_build_env/Library/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/ProgramData/chocolatey/bin/gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/bld/simage_1556231733385/work/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):D:/bld/simage_1556231733385/_build_env/Library/bin/ninja.exe cmTC_fec16 
    [1/2] Building C object CMakeFiles/cmTC_fec16.dir/testCCompiler.c.obj
    FAILED: CMakeFiles/cmTC_fec16.dir/testCCompiler.c.obj 
    C:\ProgramData\chocolatey\bin\gcc.exe   -MD -GL -o CMakeFiles/cmTC_fec16.dir/testCCompiler.c.obj   -c testCCompiler.c
    gcc.exe: error: unrecognized command line option '-GL'; did you mean '-L'?
    ninja: build stopped: subcommand failed.
```

**Comment by isuruf** [comment] 2019-04-26 07:34
Duplicate of https://github.com/conda-forge/conda-forge.github.io/issues/714

**Closed by isuruf** 2019-04-26 07:34 UTC
