### ISSUE TITLE
Rerendering oddness

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-smithy#223] opened 2016-07-09 09:48 UTC
As discussed at https://gitter.im/conda-forge/conda-forge.github.io?at=5780c78b7aeb0805278aef48, looks like there were two (of 5) rerendering issues overnight after I rebuild the conda-forge-maint image. 

Pertinent PRs https://github.com/conda-forge/bob.db.multipie-feedstock/pull/3 and https://github.com/conda-forge/bob.ip.color-feedstock/pull/6/files.

I'm unable to look at this for the next day or two, so have disabled the scheduled task to prevent any more of these.

Ping @183amir.

**Comment by jakirkham** [comment] 2016-07-23 15:16
I think it may be an issue in `conda-build-all`. Though I have had a very hard time reproducing it. See this issue ( https://github.com/SciTools/conda-build-all/issues/49 ).

**Comment by jakirkham** [comment] 2016-08-24 06:35
For a recent re-rendering with `conda-smithy` on one of the problematic feedstocks, please see PR ( https://github.com/conda-forge/bob.db.multipie-feedstock/pull/4 ).

**Comment by jakirkham** [comment] 2016-08-24 06:40
Also for another example, please see PR ( https://github.com/conda-forge/bob.ip.color-feedstock/pull/8 ).

**Comment by pelson** [comment] 2016-08-24 07:05
So I think we can close this. With a following wind, I'll be re-enabling the MNT PRs for rerendering soon.

**Comment by 183amir** [comment] 2016-08-24 08:30
Thank you for looking into this.

**Comment by pelson** [comment] 2016-08-24 09:28
Hmmm. Still seeing some problems with a rerendering at cartopy... https://github.com/conda-forge/cartopy-feedstock/pull/15.

**Comment by jakirkham** [comment] 2016-08-24 13:32
So that exact case was the inspiration of issue ( https://github.com/SciTools/conda-build-all/issues/49 ). I'm wondering if this is not also a `conda-build-all` issue.

**Comment by 183amir** [comment] 2016-08-27 16:21
https://github.com/conda-forge/bob.ip.optflow.hornschunck-feedstock/pull/5

**Comment by jakirkham** [comment] 2016-08-27 16:45
Do you need all of those things as build dependencies, @183amir? If not, try removing as many as possible and then re-render manually. I'd be curious to know if that fixes it as I have seen similar issues with build dependencies and odd re-rendering and was able to fix it that way.

**Comment by 183amir** [comment] 2016-08-27 16:54
They are not that many and yes they are needed.

**Comment by jakirkham** [comment] 2016-08-27 17:13
Well I tried to reproduce that re-rendering locally, but was unable to.

**Comment by jakirkham** [comment] 2016-08-27 22:05
Here is another one ( https://github.com/conda-forge/python-neo-feedstock/pull/4 ). 😒

**Comment by jakirkham** [comment] 2016-08-27 22:14
This one shows a similar problem, but only on AppVeyor AFAICT. ( https://github.com/conda-forge/hdf5-feedstock/pull/36 )

**Comment by jakirkham** [comment] 2016-08-27 22:23
In all cases thus far, I seem to be unable to reproduce this locally. Here is what I'm using in my environment.

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/osx-64/anaconda-client-1.5.1-py27_0.tar.bz2#58eb619946a8ffd406b01d391081d2b6
https://conda.anaconda.org/conda-forge/osx-64/anaconda-verify-1.2.0-py27_0.tar.bz2#810a9b95a45a431adce96a13766ab895
https://repo.continuum.io/pkgs/free/osx-64/appnope-0.1.0-py27_0.tar.bz2#1779b437f4e168c687106e13215f3bc9
https://conda.anaconda.org/conda-forge/osx-64/backports.shutil_get_terminal_size-1.0.0-py27_0.tar.bz2#b93a77158f86fd48012024ca0f3fd135
https://conda.anaconda.org/conda-forge/osx-64/ca-certificates-2016.8.2-3.tar.bz2#7b5f74dbc6c8c16262eaff058eff8e90
https://conda.anaconda.org/conda-forge/osx-64/certifi-2016.8.2-py27_0.tar.bz2#d743c1b84b79740bc847677b10007015
https://conda.anaconda.org/conda-forge/osx-64/clyent-1.2.1-py27_0.tar.bz2#f7d8234f39f977ef99b4f3d0422d2061
https://conda.anaconda.org/conda-forge/osx-64/conda-4.1.11-py27_1.tar.bz2#ea4e1ce0aaf2bd697b70c3a7007eb967
https://repo.continuum.io/pkgs/free/osx-64/conda-build-1.21.14-py27_0.tar.bz2#ba8c7efeeb5e4adb1e044d7a290e852f
https://conda.anaconda.org/conda-forge/osx-64/conda-build-all-0.13.3-py27_0.tar.bz2#bed496b2acccc50126161d650f80a5eb
https://conda.anaconda.org/conda-forge/osx-64/conda-env-2.5.2-py27_0.tar.bz2#008309f2f77bbd75c04b469cb7b8e529
https://conda.anaconda.org/conda-forge/osx-64/conda-execute-0.6.0-py27_0.tar.bz2#d6bc073661cec6ce6004d87fed07302a
https://conda.anaconda.org/conda-forge/osx-64/conda-smithy-1.1.2-py27_1.tar.bz2#30c497dc62355eae93e8dd65726d1dd5
https://conda.anaconda.org/conda-forge/osx-64/constructor-1.3.1-py27_0.tar.bz2#ff1a3ea752f34ba918ae75bc63c406c8
https://conda.anaconda.org/conda-forge/osx-64/curl-7.49.1-1.tar.bz2#9d251b0254906a6f836cdf07f21f31a9
https://conda.anaconda.org/conda-forge/osx-64/decorator-4.0.10-py27_0.tar.bz2#411c75b721f2264945a0a500313ce285
https://conda.anaconda.org/conda-forge/osx-64/expat-2.1.0-2.tar.bz2#a3b339d3f6f85a1f05d00902f182a717
https://conda.anaconda.org/conda-forge/osx-64/funcsigs-1.0.2-py27_0.tar.bz2#09c5aabb473be58d05e929e00e445301
https://conda.anaconda.org/conda-forge/osx-64/gitdb-0.6.4-py27_0.tar.bz2#6c69e096831192e3712f6846e2407ace
https://conda.anaconda.org/conda-forge/osx-64/gitpython-2.0.8-py27_0.tar.bz2#9619cd11bed0afb831f47e76f8451fdc
https://conda.anaconda.org/conda-forge/osx-64/ipython-5.1.0-py27_0.tar.bz2#2330392f97573d857922a34030cc5953
https://conda.anaconda.org/conda-forge/osx-64/ipython_genutils-0.1.0-py27_0.tar.bz2#c39dd49339a62d35feee6a5cf513cfc3
https://conda.anaconda.org/conda-forge/osx-64/jinja2-2.8-py27_1.tar.bz2#c4b60b9602b0423d455ea51199c9e783
https://conda.anaconda.org/conda-forge/osx-64/libconda-4.0.0-py27_0.tar.bz2#2fad2c0a63a92b7d36c05d27649d0fdd
https://conda.anaconda.org/conda-forge/osx-64/markupsafe-0.23-py27_0.tar.bz2#262142996e4654af63147a9d3bf3ac9c
https://conda.anaconda.org/conda-forge/osx-64/mock-2.0.0-py27_0.tar.bz2#87ca8332cfcf1b16cd89f626f926540c
https://conda.anaconda.org/conda-forge/osx-64/ncurses-5.9-8.tar.bz2#cd123bc6abcd97fedca8f0352343d4e0
https://conda.anaconda.org/conda-forge/osx-64/openssl-1.0.2h-2.tar.bz2#a3d896577bd08d905f0caf9f13d8dee4
https://conda.anaconda.org/conda-forge/osx-64/pathlib2-2.1.0-py27_0.tar.bz2#4e313791d96df62ca865791e2d47f5b5
https://conda.anaconda.org/conda-forge/osx-64/pbr-1.10.0-py27_0.tar.bz2#b8e45dce30bc7451d24d0d1e2f6652fa
https://conda.anaconda.org/conda-forge/osx-64/pexpect-4.2.0-py27_1.tar.bz2#0775e1a447399197291a910369ecfdc5
https://conda.anaconda.org/conda-forge/osx-64/pickleshare-0.7.3-py27_0.tar.bz2#cb8ede7a751461d9d97ddb6a4432adc1
https://conda.anaconda.org/conda-forge/osx-64/pip-8.1.2-py27_0.tar.bz2#8fcadb76c7405cc87df9d87972beae06
https://conda.anaconda.org/conda-forge/osx-64/prompt_toolkit-1.0.6-py27_0.tar.bz2#1266f41c432fe184f8ee291928e383a5
https://conda.anaconda.org/conda-forge/osx-64/psutil-4.3.0-py27_0.tar.bz2#434bcdb3e6d6527f902bfc96391d0e64
https://conda.anaconda.org/conda-forge/osx-64/ptyprocess-0.5.1-py27_0.tar.bz2#4dddb42d98695b23074a5e58088d75dd
https://conda.anaconda.org/conda-forge/osx-64/pycosat-0.6.1-py27_0.tar.bz2#a1591f26e289fe30b060b15fa44915bf
https://conda.anaconda.org/conda-forge/osx-64/pycrypto-2.6.1-py27_0.tar.bz2#dc477943e87ac96a2997c8f754055d2c
https://conda.anaconda.org/conda-forge/osx-64/pygithub-1.27.1-py27_0.tar.bz2#fcaed4a21d9e935ba2ee0e92b33b9bf2
https://conda.anaconda.org/conda-forge/osx-64/pygments-2.1.3-py27_1.tar.bz2#402439db303527051aaf6783c5bfbc5e
https://conda.anaconda.org/conda-forge/osx-64/python-2.7.12-0.tar.bz2#ca496049404ecce79abf128e2edd5976
https://conda.anaconda.org/conda-forge/osx-64/python-dateutil-2.5.3-py27_0.tar.bz2#0eeb5b22674d87f2a356a420265aa22d
https://repo.continuum.io/pkgs/free/osx-64/python.app-1.2-py27_4.tar.bz2#1c7d5c9ba62c7fdb7ab4559b1d430c67
https://conda.anaconda.org/conda-forge/osx-64/pytz-2016.6.1-py27_0.tar.bz2#181a0826480cf320d04ac1ea92926731
https://conda.anaconda.org/conda-forge/osx-64/pyyaml-3.11-py27_0.tar.bz2#60f8bd3838e9db54b254ad6a7901306f
https://conda.anaconda.org/conda-forge/osx-64/readline-6.2-0.tar.bz2#f06b2edf928df6badf0e068dbaea6abd
https://conda.anaconda.org/conda-forge/osx-64/requests-2.10.0-py27_0.tar.bz2#be8a3716ffcbcc1a55896bc3b41f8206
https://conda.anaconda.org/conda-forge/osx-64/ruamel.ordereddict-0.4.6-py27_0.tar.bz2#f2c790cf8b88fe5d5d03e411dd0dbf93
https://conda.anaconda.org/conda-forge/osx-64/ruamel.yaml-0.11.11-py27_1.tar.bz2#5f4b4752db4a177c64415ae9d3c663df
https://conda.anaconda.org/conda-forge/osx-64/ruamel_yaml-0.11.7-py27_0.tar.bz2#3ef49083f43c7c06542ed76004e6af06
https://conda.anaconda.org/conda-forge/osx-64/setuptools-25.1.6-py27_0.tar.bz2#2afaad562e94c00ba8f30a6c718c6424
https://conda.anaconda.org/conda-forge/osx-64/simplegeneric-0.8.1-py27_0.tar.bz2#28bc5b39241628a2981f08851aedaf64
https://conda.anaconda.org/conda-forge/osx-64/six-1.10.0-py27_0.tar.bz2#2cbbdeaafac48793225bac5dd78eb7fb
https://conda.anaconda.org/conda-forge/osx-64/smmap-0.9.0-py27_0.tar.bz2#fb498f366723564b81a8a425dd7605f9
https://conda.anaconda.org/conda-forge/osx-64/sqlite-3.13.0-1.tar.bz2#194695ce32f8752cdf1805c4ad8bdc42
https://conda.anaconda.org/conda-forge/osx-64/tk-8.5.19-0.tar.bz2#c601b4af479579ac7890547a8ce2b761
https://conda.anaconda.org/conda-forge/osx-64/traitlets-4.2.2-py27_0.tar.bz2#b26e048b3eb82fd709668e53bf110188
https://conda.anaconda.org/conda-forge/osx-64/wcwidth-0.1.7-py27_0.tar.bz2#c4a3f3151c473951c05168d7e99af212
https://conda.anaconda.org/conda-forge/osx-64/wheel-0.29.0-py27_0.tar.bz2#248dc566a5c38a670479e7914c1a8e06
https://conda.anaconda.org/conda-forge/osx-64/yaml-0.1.6-0.tar.bz2#d954f6a976cee816fec8d4a24c6d7f32
https://conda.anaconda.org/conda-forge/osx-64/zlib-1.2.8-3.tar.bz2#03b6fcc7a5e1a471e74049665e1c06b0
```

**Comment by jakirkham** [comment] 2016-09-07 02:30
Here's another odd one ( https://github.com/conda-forge/python-marisa-trie-feedstock/pull/1 ). 😕

**Comment by jakirkham** [comment] 2016-09-07 04:48
This one loses NumPy and Python ( https://github.com/conda-forge/qutip-feedstock/pull/10 ).

**Comment by jakirkham** [comment] 2016-09-09 04:10
Happening to `matplotlib` manual renderings now too, @pelson. ( https://github.com/conda-forge/matplotlib-feedstock/pull/54 )

**Comment by 183amir** [comment] 2016-09-11 08:16
https://github.com/conda-forge/bob.ip.base-feedstock/pull/8
It's building for one python case only while it shouldn't

**Comment by jakirkham** [comment] 2016-09-11 14:58
xref: https://github.com/conda-forge/glib-feedstock/pull/9

**Comment by jakirkham** [comment] 2016-09-19 02:43
Also PR ( https://github.com/conda-forge/bob.db.utfvp-feedstock/pull/2 ).

**Comment by jakirkham** [comment] 2016-09-19 03:18
It's weird as this seems to happen to the `bob`s more often than not. Is there something funny about having `.` in the name that is causing that case?

**Comment by 183amir** [comment] 2016-09-19 07:50
Since there are at least 65 bob packages and you see them often.

**Comment by jakirkham** [comment] 2016-09-22 02:58
Maybe. I just haven't seen the bot do it correctly on one of those feedstocks yet. Not saying this problem is in anyway exclusive to them as it clearly happens in other cases too. Just wondering if there is something we can learn from those failures.

**Comment by jakirkham** [comment] 2016-09-22 02:59
These two re-renderings have the same issue.

* https://github.com/conda-forge/scikit-learn-feedstock/pull/9
* https://github.com/conda-forge/scikit-learn-feedstock/pull/10

**Comment by 183amir** [comment] 2016-09-22 09:42
> I just haven't seen the bot do it correctly on one of those feedstocks yet.

https://github.com/conda-forge/bob.io.video-feedstock/pull/7
https://github.com/conda-forge/bob.io.matlab-feedstock/pull/8
https://github.com/conda-forge/bob.io.audio-feedstock/pull/8
https://github.com/conda-forge/bob.blitz-feedstock/pull/9
https://github.com/conda-forge/bob.learn.libsvm-feedstock/pull/8

**Comment by jakirkham** [comment] 2016-09-28 03:15
Those are all pinning PRs though. That is a different bot and script. Has the re-rendering bot ever done something correctly for one of those feedstocks?

**Comment by jakirkham** [comment] 2016-09-28 03:16
Had a round of re-rendering PRs that were sour again with `scikit-learn`. Still can't reproduce this locally.

https://github.com/conda-forge/scikit-learn-feedstock/pull/14
https://github.com/conda-forge/scikit-learn-feedstock/pull/15
https://github.com/conda-forge/scikit-learn-feedstock/pull/16

**Comment by 183amir** [comment] 2016-09-28 06:43
> Those are all pinning PRs though. That is a different bot and script. Has the re-rendering bot ever done something correctly for one of those feedstocks?

I don't remember. All my feedstocks were old and I re-rendered them manually yesterday.

**Comment by 183amir** [comment] 2016-09-28 14:41
I got a rerendering oddness in my laptop; steps to reproduce:
```sh
$ git clone bob-feedstock
$ cd bob-feedstock
$ git checkout 5f6e3fe
$ conda-smithy rerender
$ git diff
```
```patch
git diff
diff --git a/.travis.yml b/.travis.yml
index 84e8173..9e9f112 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,7 +1,9 @@
 # This file was generated automatically from conda-smithy. To update this configuration,
 # update the conda-forge.yaml and/or the recipe/meta.yaml.
 
-language: objective-c
+language: generic
+
+os: osx
 
 env:
   matrix:
@@ -28,16 +30,12 @@ install:
       bash $MINICONDA_FILE -b
 
       export PATH=/Users/travis/miniconda3/bin:$PATH
-
-      conda config --set show_channel_urls true
-      conda update --yes conda
-      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
       conda config --add channels conda-forge
-      
+      conda config --set show_channel_urls true
+      conda install --yes --quiet conda-forge-build-setup
+      source run_conda_forge_build_setup
 
 script:
   - conda build ./recipe
 
-after_success:
-
   - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
diff --git a/README.md b/README.md
index 459c629..aa11a12 100644
--- a/README.md
+++ b/README.md
@@ -1,7 +1,7 @@
 About bob
 =========
 
-Home: http://idiap.github.io/bob/
+Home: https://www.idiap.ch/software/bob/
 
 Package license: Modified BSD License (3-clause)
 
@@ -38,7 +38,7 @@ About conda-forge
 
 conda-forge is a community-led conda channel of installable packages.
 In order to provide high-quality builds, the process has been automated into the
-conda-forge GitHub organization. The conda-forge organization contains one repository 
+conda-forge GitHub organization. The conda-forge organization contains one repository
 for each of the installable packages. Such a repository is known as a *feedstock*.
 
 A feedstock is made up of a conda recipe (the instructions on what and how to build
@@ -70,9 +70,9 @@ Terminology
 Current build status
 ====================
 
-Linux: [![Circle CI](https://circleci.com/gh/conda-forge/bob-feedstock.svg?style=svg)](https://circleci.com/gh/conda-forge/bob-feedstock)
-OSX: [![TravisCI](https://travis-ci.org/conda-forge/bob-feedstock.svg?branch=master)](https://travis-ci.org/conda-forge/bob-feedstock) 
-Windows: [![AppVeyor](https://ci.appveyor.com/api/projects/status/github/conda-forge/bob-feedstock?svg=True)](https://ci.appveyor.com/project/conda-forge/bob-feedstock/branch/master)
+Linux: [![Circle CI](https://circleci.com/gh/conda-forge/bob-feedstock.svg?style=shield)](https://circleci.com/gh/conda-forge/bob-feedstock)
+OSX: [![TravisCI](https://travis-ci.org/conda-forge/bob-feedstock.svg?branch=master)](https://travis-ci.org/conda-forge/bob-feedstock)
+Windows: ![](https://cdn.rawgit.com/conda-forge/conda-smithy/90845bba35bec53edac7a16638aa4d77217a3713/conda_smithy/static/disabled.svg)
 
 Current release info
 ====================
@@ -83,16 +83,21 @@ Downloads: [![Anaconda-Server Badge](https://anaconda.org/conda-forge/bob/badges
 Updating bob-feedstock
 ======================
 
-If you would like to improve the bob recipe, please take the normal
-route of forking this repository and submitting a PR. Upon submission, your changes will
-be run on the appropriate platforms to give the reviewer an opportunity to confirm that the
-changes result in a successful build. Once merged, the recipe will be re-built and uploaded
-automatically to the conda-forge channel, whereupon they will be available for everybody to
-install and use.
+If you would like to improve the bob recipe or build a new
+package version, please fork this repository and submit a PR. Upon submission,
+your changes will be run on the appropriate platforms to give the reviewer an
+opportunity to confirm that the changes result in a successful build. Once
+merged, the recipe will be re-built and uploaded automatically to the
+`conda-forge` channel, whereupon the built conda packages will be available for
+everybody to install and use from the `conda-forge` channel.
+Note that all branches in the conda-forge/bob-feedstock are
+immediately built and any created packages are uploaded, so PRs should be based
+on branches in forks and branches in the main repository should only be used to
+build distinct package versions.
 
 In order to produce a uniquely identifiable distribution:
  * If the version of a package **is not** being increased, please add or increase
-   the [``build/number``](http://conda.pydata.org/docs/building/meta-yaml.html#build-number-and-string). 
+   the [``build/number``](http://conda.pydata.org/docs/building/meta-yaml.html#build-number-and-string).
  * If the version of a package **is** being increased, please remember to return
    the [``build/number``](http://conda.pydata.org/docs/building/meta-yaml.html#build-number-and-string)
    back to 0.
diff --git a/ci_support/run_docker_build.sh b/ci_support/run_docker_build.sh
index c8af217..36ec4f8 100755
--- a/ci_support/run_docker_build.sh
+++ b/ci_support/run_docker_build.sh
@@ -14,7 +14,6 @@ config=$(cat <<CONDARC
 
 channels:
  - conda-forge
-
  - defaults # As we need conda-build
 
 conda-build:
@@ -39,26 +38,13 @@ echo "$config" > ~/.condarc
 # A lock sometimes occurs with incomplete builds. The lock file is stored in build_artefacts.
 conda clean --lock
 
-conda update --yes --all
-conda install --yes conda-build
-conda info
+conda install --yes --quiet conda-forge-build-setup
+source run_conda_forge_build_setup
 
-# Embarking on 3 case(s).
+# Embarking on 1 case(s).
     set -x
     export CONDA_PY=27
     set +x
     conda build /recipe_root --quiet || exit 1
     /feedstock_root/ci_support/upload_or_check_non_existence.py /recipe_root conda-forge --channel=main || exit 1
-
-    set -x
-    export CONDA_PY=34
-    set +x
-    conda build /recipe_root --quiet || exit 1
-    /feedstock_root/ci_support/upload_or_check_non_existence.py /recipe_root conda-forge --channel=main || exit 1
-
-    set -x
-    export CONDA_PY=35
-    set +x
-    conda build /recipe_root --quiet || exit 1
-    /feedstock_root/ci_support/upload_or_check_non_existence.py /recipe_root conda-forge --channel=main || exit 1
```
```sh
$ conda list conda       
# packages in environment at /home/amir/miniconda:
#
Using Anaconda API: https://api.anaconda.org
conda-build               2.0.1                    py35_0    defaults
anaconda-client           1.5.1                    py35_0    conda-forge
conda                     4.1.11                   py35_1    conda-forge
conda-build-all           1.0.0                    py35_0    conda-forge
conda-env                 2.5.2                    py35_0    conda-forge
conda-execute             0.7.0                    py35_1    conda-forge
conda-smithy              1.2.0                    py35_1    conda-forge
conda-manager             0.4.0                    py35_0    defaults
```

**Comment by jakirkham** [comment] 2016-09-28 17:26
So I see this issue. Though I don't think this is due to re-rendering oddness. It has only stripped Python versions on Linux, but it left 2.7.

If you look at [`bob.blitz`]( https://circleci.com/gh/conda-forge/bob.blitz-feedstock/26 ), it's Linux build failed to upload Python 3.4 and 3.5. Try giving that a restart to get the rest of the Linux packages deployed and then retry. Also would suggest double checking all the rest of your dependencies to ensure they got built and uploaded properly.

Note: The upload issue appears to related to issue ( https://github.com/Anaconda-Platform/support/issues/60 ). We have a potential workaround in `conda-smithy` `master`, but it requires a new release ( https://github.com/conda-forge/conda-smithy/issues/305 ).

**Comment by jakirkham** [comment] 2016-09-29 20:52
It appears PR ( https://github.com/conda-forge/conda-forge-maintenance/pull/7 ) fixes this. Am going to close this out as it seems to have fixed many bad re-renderings and is generally working. If you do see this issue again, please ping and we can reopen.

**Comment by jakirkham** [comment] 2016-11-01 11:28
Saw a recurrence of this in PR ( https://github.com/conda-forge/kuyruk-feedstock/pull/2 ).

cc @frol

**Comment by MSeifert04** [comment] 2016-11-01 13:49
Is this the same Bug that happened to me in https://github.com/conda-forge/iteration_utilities-feedstock/pull/1?

**Comment by jakirkham** [comment] 2016-11-02 13:25
Another case is occurring in PR ( https://github.com/conda-forge/nilearn-feedstock/pull/8 ).

**Comment by jakirkham** [comment] 2016-11-02 13:27
Quite possibly @MSeifert04 . The only thing we have found to work is using everything possible from `conda-forge` in the `root` environment. Though it remains unclear why that should matter.

**Comment by frol** [comment] 2016-11-02 13:36
@jakirkham Just for your info, yesterday, re-rendering wasn't working correctly for kuyruk feedstock even after I downgraded smithy, but today, I have just retried and re-rendering didn't drop the matrix... It sounds like the issue is somewhat external.

**Comment by jakirkham** [comment] 2016-11-02 13:39
It could be. I have been somewhat suspicious that this is a response to not being able to download some build dependencies. Though I'm not sure why we don't just get an exception.

Also anyone experiencing this should make sure `conda-build-all` is also upgraded to latest.

**Comment by jakirkham** [comment] 2016-11-02 13:43
cc @lesteve

**Comment by jakirkham** [comment] 2016-11-16 09:48
Another instance in PR ( https://github.com/conda-forge/libadjoint-feedstock/pull/1 ).

**Comment by jakirkham** [comment] 2016-11-16 09:50
Also, `pathos` was created with an improper rendering. The re-rendering bot appears to have fixed it though. 😕

xref: https://github.com/conda-forge/pathos-feedstock/pull/1

**Comment by jakirkham** [comment] 2017-01-09 14:51
FYI think part of the issue is that `conda-smithy` use channels from one's `.condarc` to re-render. ( https://github.com/conda-forge/conda-smithy/issues/387 ) We are making changes so that `.condarc` will be ignored entirely and feedstock level settings will control the channels used to re-render. This should hopefully fix this issue.

**Closed** 2017-01-10 23:32 UTC
Labels: bug
