### ISSUE TITLE
Drone broken for staged-recipes CI

### ISSUE THREAD

**Issue by juliotux** [conda-forge/conda-smithy#1148] opened 2019-09-13 12:21 UTC
Since yesterday, `staged-recipes` Travis-CI build is broken due to a Drone problem. All CI builds for `staged-recipes` fail with:

```
 Summary for conda-forge/astrometry-feedstock (can take ~30s):
 * conda-forge/astrometry-feedstock already enabled on travis-ci
 * conda-forge/astrometry-feedstock enabled on CircleCI
 * conda-forge/astrometry-feedstock already enabled on azure pipelines
 * conda-forge/astrometry-feedstock already enabled on appveyor
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 477, in main
    args.subcommand_func(args)
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 248, in __call__
    ci_register.add_project_to_drone(owner, repo)
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 149, in add_project_to_drone
    response.raise_for_status()
  File "/home/travis/miniconda/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cloud.drone.io/api/repos/conda-forge/astrometry-feedstock
Traceback (most recent call last):
  File ".travis_scripts/create_feedstocks.py", line 171, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/home/travis/miniconda/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/tmp/tmpp0y5mst1__feedstocks/astrometry-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1.
```

However, manual access to the 404 URL is possible.

Is this related to #1146 or #1147 ?

Probably introduced by 4fba30ad3e697eb61224d52b0a06ff1683bb8419

**Comment by scopatz** [comment] 2019-09-13 19:34
Yep, I am seeing this

**Comment by isuruf** [comment] 2019-09-13 19:42
Duplicate of #1146 and #1147

**Closed by isuruf** 2019-09-13 19:42 UTC
