### ISSUE TITLE
Error with Python 3.6

### ISSUE THREAD

**Issue by ericmjl** [conda-forge/conda-smithy#450] opened 2017-02-02 01:10 UTC
I downloaded the latest version of the Anaconda distribution of Python and made a clean Anaconda install from it (today, 1 February 2017), so that I could get Python 3.6.

However, when I try installing `conda-smithy`, I get the following error:

```bash
$ conda install conda-smithy
Fetching package metadata .............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - conda-smithy -> conda-build-all -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

I'm not sure if I'm doing something wrong here?

Also, is there a reason why python 2.7 is showing up here?

**Comment by gustavla** [comment] 2017-02-02 01:22
I have also noticed that 2.7 keeps popping up when packages do not support 3.6. I think it's just showing one of the supported pythons (perhaps just the first one in the list). If you run `conda info conda-smithy` you will see that it supports python 3.5 too, so it could have equally said `... -> python 3.5*`.

I'm also looking to install `conda-smithy` under a 3.6 root by the way.

**Comment by ericmjl** [comment] 2017-02-02 02:52
I checked `conda info conda-smithy`, and indeed the highest version of Python supported is py35. I'm right now still a noob with the conda build process, but I'm wondering if a PR to the conda-smithy feedstock would help bump it to support py36?

**Comment by gustavla** [comment] 2017-02-02 04:19
The PR #422 suggests that 3.6 support has already been added. Not sure if it's imcomplete, or if the problem is simply that all the requirements have to support 3.6 too. For instance, I don't see 3.6 support for `pygithub` (which is a dependency of conda-smithy), so I guess that would have to be addressed first.

**Comment by ocefpaf** [comment] 2017-02-02 09:01
> or if the problem is simply that all the requirements have to support 3.6 too

That is probably it. Can you send re-render PRs to `pygithub` to get a PY36 build there?

**Comment by ericmjl** [comment] 2017-02-02 16:59
@ocefpaf: on the job.

**Comment by jakirkham** [comment] 2017-02-06 04:29
> The PR #422 suggests that 3.6 support has already been added.

That PR is about something totally different. The PR body explains this in more detail.

@ocefpaf and @ericmjl are correct in deducing one needs the dependencies satisfied on Python 3.6 to get a Python 3.6 package for `conda-smithy`. Thanks for getting after that in the interim guys.

**Comment by jakirkham** [comment] 2017-02-19 23:18
Fixed by PR ( https://github.com/conda-forge/conda-smithy-feedstock/pull/68 ).

**Closed by jakirkham** 2017-02-19 23:18 UTC
