### ISSUE TITLE
conda smithy register-ci raises ValueError for appveyor

### ISSUE THREAD

**Issue by shadowwalkersb** [conda-forge/conda-smithy#438] opened 2017-01-17 01:41 UTC
The command seems to complete successfully, but still an exception is raised. I remember posting this before, but then I closed it to cleanup my issue list since there was no response, AFAIR. #303 seems to report the same thing. No response there for 4 months. 😞 

```
$ conda smithy register-ci --feedstock_directory szip-feedstock --user shadowwalkersb
CI Summary for shadowwalkersb/szip-feedstock (can take ~30s):
 * Registered on travis-ci
 * shadowwalkersb/szip-feedstock enabled on CircleCI
 * shadowwalkersb/szip-feedstock has been enabled on appveyor
Traceback (most recent call last):
  File "/Users/shadow_walker/anaconda/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/Users/shadow_walker/anaconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 289, in main
    args.subcommand_func(args)
  File "/Users/shadow_walker/anaconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 179, in __call__
    ci_register.appveyor_configure(owner, repo)
  File "/Users/shadow_walker/anaconda/lib/python2.7/site-packages/conda_smithy/ci_register.py", line 157, in appveyor_configure
    raise ValueError(response)
ValueError: <Response [404]>
```

**Comment by jakirkham** [comment] 2017-02-19 23:21
Closing as duplicate of issue ( https://github.com/conda-forge/conda-smithy/issues/303 ).

**Closed by jakirkham** 2017-02-19 23:21 UTC
