### ISSUE TITLE
.scripts/run_docker_build.sh: Permission denied

### ISSUE THREAD

**Issue by xylar** [conda-forge/conda-smithy#2102] opened 2024-10-26 17:04 UTC
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

I just did a rerender on the esmf feedstock:
https://github.com/conda-forge/esmf-feedstock/pull/123
and it changed permissions on various scripts, e.g.:
 .scripts/run_docker_build.sh 100755 → 100644
This results in immediate build failures:
```
/home/vsts/work/_temp/7845e445-8e00-430c-b0af-d91fdc873645.sh: line 12: .scripts/run_docker_build.sh: Permission denied
```

### Installed packages

N/A

### Environment info

N/A

**Comment by beckermr** [comment] 2024-10-30 10:00
This was a bug in the rerendering webservices and is a dupe of https://github.com/conda-forge/conda-forge-webservices/issues/743

PR https://github.com/conda-forge/conda-forge-webservices/pull/748 likely fixed this.

Can you retry and confirm?

**Comment by xylar** [comment] 2024-10-30 13:06
@beckermr, wonderful, that's fixed it.

**Closed** 2024-10-30 13:07 UTC
Labels: bug
