### ISSUE TITLE
Custom env variable using `github_actions`

### ISSUE THREAD

**Issue by hadim** [conda-forge/conda-smithy#1532] opened 2021-10-27 19:38 UTC
We are currently using the `azure` provider on a private forge using conda-smithy and it works great. I am trying to experiment using the new `github_actions` but I can't find a way to inject custom env variables from CI secrets into the build.

For context, we are using 3 custom env variables (mostly token and password) that we need during the build. Those are configured in the Library section in Azure and in the feedstock with:

```yaml
docker:
  run_args: >-
    -e TOKEN_1
    -e TOKEN_2
    -e TOKEN_3
```

When using `github_actions`, I have added the secrets into the feedstock GH repository but I don't think it's possible to actually inject those into the GH action workflow since they need to be set explicitly with `{{ secrets.TOKEN_1 }}`.

Can you confirm it's not possible to do that right now (besides manually altering the generated workflow file)? Can you think of a workaround?

**Comment by isuruf** [comment] 2021-11-03 08:34
Duplicate of https://github.com/conda-forge/conda-smithy/issues/1162

**Closed by isuruf** 2021-11-03 08:34 UTC

**Comment by hadim** [comment] 2021-11-03 12:53
For the record, it's very easy to inject secrets a conda smithy CI provider. In `conda-forge.yml`, you must set the secret env variable with:

```yaml
secrets:
  - INVIVOAI_ANACONDA_TOKEN
  - INVIVODEV_GITHUB_USERNAME
  - INVIVODEV_GITHUB_PASSWORD
```

**Comment by hadim** [comment] 2021-11-03 12:53
For the record, it's very easy to inject secrets a conda smithy CI provider. In `conda-forge.yml`, you must set the secret env variable with:

```yaml
secrets:
  - SECRET_1
  - SECRET_2
  - SECRET_3
```
